version: "3.4"
services:
  backend-blue:
    image: gitlab.praktikum-services.ru:5050/a.lisitsin/sausage-store/sausage-backend:latest
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_HOST: ${VAULT_HOST}
      REPORT_PATH: ${REPORT_PATH}
      LOG_PATH: ${LOG_PATH}
      VIRTUAL_HOST: sausage-store
    networks:
      - sausage-store
  
  backend-green:
    image: gitlab.praktikum-services.ru:5050/a.lisitsin/sausage-store/sausage-backend:latest
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_HOST: ${VAULT_HOST}
      REPORT_PATH: ${REPORT_PATH}
      LOG_PATH: ${LOG_PATH}
      VIRTUAL_HOST: sausage-store
    networks:
      - sausage-store
  
  backend-report:
    image: gitlab.praktikum-services.ru:5050/a.lisitsin/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    restart: always
    environment:
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_HOST: ${VAULT_HOST}
    networks:
      - sausage-store
  
  frontend:
    image: gitlab.praktikum-services.ru:5050/a.lisitsin/sausage-store/sausage-frontend:latest
    restart: always
    container_name: sausage-frontend
    environment:
      - DEFAULT_HOST=sausage-store
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - sausage-store
  
  vault:
    image: vault
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
      VAULT_SERVER: ${VAULT_SERVER}
      VAULT_ADDR: ${VAULT_ADDR}
      DATASRC_PASS_PSQL: ${DATASRC_PASS_PSQL}
      MONGODB_URL: ${MONGODB_URL}
      PSQL_DATASRC: ${PSQL_DATASRC}
      DATASRC_USER: ${DATASRC_USER}
      TEST_DATASRC_PSQL_USER: ${TEST_DATASRC_PSQL_USER}
      TEST_DATASRC_PSQL_PASS: ${TEST_DATASRC_PSQL_PASS}
    ports:
      - "8200:8200"
    networks:
      - sausage-store

networks:
  sausage-store: